## Switches
set_property PACKAGE_PIN V17 [get_ports {gray[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gray[0]}]
set_property PACKAGE_PIN V16 [get_ports {gray[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gray[1]}]
set_property PACKAGE_PIN W16 [get_ports {gray[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gray[2]}]
set_property PACKAGE_PIN W17 [get_ports {gray[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gray[3]}]
 
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {segments[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property PACKAGE_PIN W6 [get_ports {segments[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property PACKAGE_PIN U8 [get_ports {segments[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property PACKAGE_PIN V5 [get_ports {segments[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property PACKAGE_PIN U7 [get_ports {segments[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]